//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1804_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araclar()
        {
            this.Kullanicis = new HashSet<Kullanici>();
        }
    
        public int Araç_No { get; set; }
        public Nullable<decimal> Araç_Fiyat { get; set; }
        public Nullable<int> Araç_Adet { get; set; }
        public string Araç_Marka { get; set; }
        public string Araç_Model { get; set; }
        public Nullable<int> Araç_Yıl { get; set; }
        public string Araç_Özellik { get; set; }
        public string Araç_Motor { get; set; }
        public string Araç_Paket { get; set; }
        public string Araç_Renk { get; set; }
        public Nullable<int> Şube_No { get; set; }
    
        public virtual Subeler Subeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
    }
}
