//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1804_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int Kullanıcı_No { get; set; }
        public string Kullanıcı_Adı { get; set; }
        public string Şifre { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Tc { get; set; }
        public Nullable<int> Şirket_Kodu { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
