//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1804_04
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaleriEntities : DbContext
    {
        public GaleriEntities()
            : base("name=GaleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araclar> Araclars { get; set; }
        public virtual DbSet<Kayit> Kayits { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Subeler> Subelers { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
    }
}
