//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1804_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Kayits = new HashSet<Kayit>();
        }
    
        public int Şirket_No { get; set; }
        public string Şirket_Adı { get; set; }
        public string Şirket_Sektör { get; set; }
        public string Şirket_Ceo { get; set; }
        public Nullable<int> Şirket_Araç_Sayısı { get; set; }
        public int Şirket_Kodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayits { get; set; }
    }
}
